[theme]
base = "light"

primaryColor = "#1F4E78"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#EAF0F6"
textColor = "#1F2937"

font = "sans serif"


[client]
toolbarMode = "minimal"


[browser]
gatherUsageStats = false
